version: '3.8'

services:
  ansible:
    build:
      context: .
      dockerfile: ./dockerfileUbuntuHost
    container_name: ansible
    volumes:
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /ansible
    tty: true
    stdin_open: true
    networks:
      - jenkins_cicd-network

  ubuntu-ssh-host-app:
    build:
      context: .
      dockerfile: ./dockerfileUbuntu
    container_name: ubuntu-ssh-host-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_cicd-network

networks:
  jenkins_cicd-network:
    external: true
